start: upgrade

upgrade:
	cd gigasecond && npm -verbose upgrade && cd ..
	cd hello-world && npm -verbose upgrade && cd ..
	cd resistor-color && npm -verbose upgrade && cd ..
	cd resistor-color-duo && npm -verbose upgrade && cd ..
	cd two-fer && npm -verbose upgrade && cd ..
